apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pythonappargo11
  name: pythonappargo11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonappargo11
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pythonappargo11
    spec:
      containers:
      - image: kodatichanikya/nodeapp:v1
        name: pythonappargo11
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-service
spec:
  type: NodePort
  ports:
  - nodePort: 30001
    port: 80
    targetPort: 5000
  selector:
    app: pythonappargo11
